# Nixpacks configuration
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.build]
cmds = ["npm install --omit=dev", "npx prisma generate", "npm run build"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"